version: '3.7'

services:
  roundrobinapi:
    image: ${DOCKER_REGISTRY-}roundrobinapi:dev
    build:
      context: .
      dockerfile: RoundRobinApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/test.pfx
      - ASPNETCORE_Kestrel__Certificates__Default__Password=testpassword
    ports:
      - 8080:80
      - 27443:443
    volumes:
      - F:\Dev\Coda:/https/
  applicationapi:
    image: ${DOCKER_REGISTRY-}applicationapi:dev
    build:
      context: .
      dockerfile: ApplicationApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 27000:80
  applicationapi-1:
    image: ${DOCKER_REGISTRY-}applicationapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 27001:80
  applicationapi-2:
    image: ${DOCKER_REGISTRY-}applicationapi:dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 27002:80
